#
#  There exist several targets which are by default empty and which can be 
#  used for execution of your targets. These targets are usually executed 
#  before and after some main targets. They are: 
#
#     .build-pre:              called before 'build' target
#     .build-post:             called after 'build' target
#     .clean-pre:              called before 'clean' target
#     .clean-post:             called after 'clean' target
#     .clobber-pre:            called before 'clobber' target
#     .clobber-post:           called after 'clobber' target
#     .all-pre:                called before 'all' target
#     .all-post:               called after 'all' target
#     .help-pre:               called before 'help' target
#     .help-post:              called after 'help' target
#
#  Targets beginning with '.' are not intended to be called on their own.
#
#  Main targets can be executed directly, and they are:
#  
#     build                    build a specific configuration
#     clean                    remove built files from a configuration
#     clobber                  remove all built files
#     all                      build all configurations
#     help                     print help mesage
#  
#
#  Available make variables:
#
#     CND_BASEDIR                base directory for relative paths
#     CND_DISTDIR                default top distribution directory (build artifacts)
#     CND_BUILDDIR               default top build directory (object files, ...)
#     CONF                       name of current configuration
#     CND_PLATFORM_${CONF}       platform name (current configuration)
#     CND_ARTIFACT_DIR_${CONF}   directory of build artifact (current configuration)
#     CND_ARTIFACT_NAME_${CONF}  name of build artifact (current configuration)
#     CND_ARTIFACT_PATH_${CONF}  path to build artifact (current configuration)
#     CND_PACKAGE_DIR_${CONF}    directory of package (current configuration)
#     CND_PACKAGE_NAME_${CONF}   name of package (current configuration)
#     CND_PACKAGE_PATH_${CONF}   path to package (current configuration)
#
# NOCDDL

define newline


endef

# Environment 
MKDIR=mkdir
CP=cp
CCADMIN=CCadmin

GFORT = gfortran -mcmodel=medium -fbacktrace
IFORT = ifort -r8 -mcmodel medium -traceback -fpe0 -diag-disable=10448
FORT = $(IFORT)
C = gcc -std=c99

BUILD_DIR = ./bin
LIB_DIR = ./lib
C_SRC_DIR = ./src/c
FORT_SRC_DIR = ./src/fortran
# Generated by the recipe below; gitignored.  Baked into every live
# Fortran binary so it can self-report which commit it was built from.
VERSION_F90 = $(FORT_SRC_DIR)/version_stamp.f90
FORT_MICRO = micro_rates.f90
FORT_MACRO = macro_diffuse_into_and_along__internal \
             macro_diffuse_into_and_along__external

# build
build: .build-pre fort

fort: fort-micro fort-macro

fort-micro: $(BUILD_DIR)/micro_rates # $(BUILD_DIR)/micro_wrapped

fort-macro: $(foreach file,$(FORT_MACRO),$(BUILD_DIR)/$(file))

shared: $(LIB_DIR)/kiss.so

# version_stamp.f90 is a tiny Fortran module holding BUILD_TAG,
# BUILD_COMMIT and BUILD_DIRTY string parameters resolved from git.  Each
# live Fortran binary `use`s it -- together with the Fortran-2008 intrinsic
# `compiler_version()` from iso_fortran_env -- and supports `--version`,
# which prints "<tag> <commit> <clean|dirty> <compiler-string>" so the
# Python wrapper can confirm the binary was built from the currently-
# checked-out source AND the expected compiler before launching a
# simulation.  The compiler info is contributed by the compiler itself at
# compile time, so no Makefile probing is needed for it.
#
# BUILD_TAG is the nearest release tag reachable from HEAD
# (`git describe --tags --abbrev=0`, e.g. "v0.3.0"); it is a human-facing
# release label only and is not used by the staleness check.  BUILD_COMMIT
# is the most recent commit *that touched src/fortran/*, not the repo HEAD.
# This way commits that change only Python/docs/etc do not flag the binary
# as stale -- only commits that actually modify the Fortran source do.
# BUILD_DIRTY is scoped the same way: tracked uncommitted changes under
# src/fortran/ flip it to "dirty".
#
# The recipe runs on every `make` (via the FORCE prerequisite below) so
# it always reflects current state, but writes via a tmp+cmp+mv pattern:
# the file's mtime only bumps when the embedded stamp actually changes,
# letting Make's normal mtime-based dependency resolution skip recompiles
# when nothing has changed.
$(VERSION_F90): FORCE
	@if git rev-parse HEAD >/dev/null 2>&1; then \
	    COMMIT=$$(git log -1 --format=%H HEAD -- $(FORT_SRC_DIR) 2>/dev/null); \
	    [ -n "$$COMMIT" ] || COMMIT=unknown; \
	    TAG=$$(git describe --tags --abbrev=0 2>/dev/null); \
	    [ -n "$$TAG" ] || TAG=unknown; \
	    if git diff --quiet HEAD -- $(FORT_SRC_DIR) 2>/dev/null; then DIRTY=clean; else DIRTY=dirty; fi; \
	else \
	    TAG=unknown; COMMIT=unknown; DIRTY=unknown; \
	fi; \
	printf 'module version_stamp\n  implicit none\n  character(len=*), parameter :: BUILD_TAG    = "%s"\n  character(len=*), parameter :: BUILD_COMMIT = "%s"\n  character(len=*), parameter :: BUILD_DIRTY  = "%s"\nend module version_stamp\n' \
	    "$$TAG" "$$COMMIT" "$$DIRTY" > $@.tmp; \
	if cmp -s $@.tmp $@ 2>/dev/null; then \
	    rm $@.tmp; \
	else \
	    mv $@.tmp $@; \
	fi

# Empty non-phony target: Make can never "find" it on disk, so it treats
# FORCE as always-newer-than-$(VERSION_F90) and re-fires that recipe on
# every build.  Marking $(VERSION_F90) itself .PHONY would also re-fire
# the recipe, but a .PHONY prerequisite is always considered out-of-date,
# which would cascade unconditional recompiles into every binary that
# depends on $(VERSION_F90).
FORCE:

# $(VERSION_F90) is passed BEFORE the program source on the compile line
# so its .mod file is produced first within a single compiler invocation,
# making the `use version_stamp` in the program resolvable.
$(BUILD_DIR)/micro_rates: $(FORT_SRC_DIR)/micro_rates.f90 $(VERSION_F90) $(BUILD_DIR)/kiss.o
	$(FORT) $(BUILD_DIR)/kiss.o $(VERSION_F90) $(FORT_SRC_DIR)/micro_rates.f90 -o $(BUILD_DIR)/micro_rates

# $(BUILD_DIR)/micro_wrapped: $(FORT_SRC_DIR)/micro_wrapped.f90 $(BUILD_DIR)/kiss.o
# 	$(FORT) $(BUILD_DIR)/kiss.o $(FORT_SRC_DIR)/micro_wrapped.f90 -o $(BUILD_DIR)/micro_wrapped

$(BUILD_DIR)/macro_diffuse_into_and_along__external: $(FORT_SRC_DIR)/macro_diffuse_into_and_along__external.f90 $(VERSION_F90) $(BUILD_DIR)/kiss.o
	$(FORT) $(BUILD_DIR)/kiss.o $(VERSION_F90) $(FORT_SRC_DIR)/macro_diffuse_into_and_along__external.f90 -o $(BUILD_DIR)/macro_diffuse_into_and_along__external

$(BUILD_DIR)/macro_diffuse_into_and_along__internal: $(FORT_SRC_DIR)/macro_diffuse_into_and_along__internal.f90 $(VERSION_F90) $(BUILD_DIR)/kiss.o
	$(FORT) $(BUILD_DIR)/kiss.o $(VERSION_F90) $(FORT_SRC_DIR)/macro_diffuse_into_and_along__internal.f90 -o $(BUILD_DIR)/macro_diffuse_into_and_along__internal

$(LIB_DIR)/kiss.so: $(C_SRC_DIR)/kiss.c
	$(C) -fPIC -std=c99 -shared -o $(LIB_DIR)/kiss.so $(C_SRC_DIR)/kiss.c

$(BUILD_DIR)/kiss.o: $(C_SRC_DIR)/kiss.c
	$(C) -c $(C_SRC_DIR)/kiss.c -o $(BUILD_DIR)/kiss.o
#	gcc -c -std=c99 $(C_SRC_DIR)/kiss.c -o $(BUILD_DIR)/kiss.o

.build-pre:

.build-post:
# Add your post 'build' code here...

# clean
clean: .clean-post
	rm -r $(BUILD_DIR)
	mkdir $(BUILD_DIR)

.clean-pre:
# Add your pre 'clean' code here...

.clean-post:
# Add your post 'clean' code here...

# clobber
clobber: .clobber-post

.clobber-pre:
# Add your pre 'clobber' code here...

.clobber-post:
# Add your post 'clobber' code here...

# all
all: .all-post

.all-pre:
# Add your pre 'all' code here...

.all-post:
# Add your post 'all' code here...

# build tests
build-tests: .build-tests-post

.build-tests-pre:
# Add your pre 'build-tests' code here...

.build-tests-post:
# Add your post 'build-tests' code here...

# run tests
test: .test-post

.test-pre: build-tests
# Add your pre 'test' code here...

.test-post:
# Add your post 'test' code here...

# help
help: .help-post

.help-pre:
# Add your pre 'help' code here...

.help-post:
# Add your post 'help' code here...
