# Makefile for the lysis fibrinolysis model.
#
# Builds the compiled artifacts the Python package shells out to or loads:
#   - Fortran micro/macro simulation binaries -> ./bin
#   - the KISS RNG shared library             -> ./lib/kiss.so
#                                                (loaded by lysis.tools.kiss)
#
# Common targets (run `make help` for the list):
#   make            build everything (Fortran binaries + kiss.so)
#   make fort       build only the Fortran binaries
#   make shared     build only lib/kiss.so
#   make clean      remove ./bin and ./lib
#   make clobber    clean + remove the generated version_stamp.f90
#
# Requirements: the Fortran targets need Intel ifort on PATH (on the
# cluster: `module load intel-compilers/2023`); `shared` needs only gcc.
# Neither ./bin nor ./lib is tracked in git -- both are created on demand.

# Environment
MKDIR = mkdir

# Fortran compiler.  The live binaries are built with Intel ifort; the
# gfortran line is kept as a documented alternative -- switch by setting
# FORT = $(GFORT).
GFORT = gfortran -mcmodel=medium -fbacktrace
IFORT = ifort -r8 -mcmodel medium -traceback -fpe0 -diag-disable=10448
FORT = $(IFORT)
C = gcc -std=c99

BUILD_DIR = ./bin
LIB_DIR = ./lib
C_SRC_DIR = ./src/c
FORT_SRC_DIR = ./src/fortran
# Generated by the recipe below; gitignored.  Baked into every live
# Fortran binary so it can self-report which commit it was built from.
VERSION_F90 = $(FORT_SRC_DIR)/version_stamp.f90
FORT_MACRO = macro_diffuse_into_and_along__internal \
             macro_diffuse_into_and_along__external

.PHONY: build all fort fort-micro fort-macro shared clean clobber help

# Default target: build all compiled artifacts.
build: fort shared

all: build

fort: fort-micro fort-macro

fort-micro: $(BUILD_DIR)/micro_rates # $(BUILD_DIR)/micro_wrapped

fort-macro: $(foreach file,$(FORT_MACRO),$(BUILD_DIR)/$(file))

shared: $(LIB_DIR)/kiss.so

# version_stamp.f90 is a tiny Fortran module holding BUILD_TAG,
# BUILD_COMMIT and BUILD_DIRTY string parameters resolved from git.  Each
# live Fortran binary `use`s it -- together with the Fortran-2008 intrinsic
# `compiler_version()` from iso_fortran_env -- and supports `--version`,
# which prints "<tag> <commit> <clean|dirty> <compiler-string>" so the
# Python wrapper can confirm the binary was built from the currently-
# checked-out source AND the expected compiler before launching a
# simulation.  The compiler info is contributed by the compiler itself at
# compile time, so no Makefile probing is needed for it.
#
# BUILD_TAG is the nearest release tag reachable from HEAD
# (`git describe --tags --abbrev=0`, e.g. "v0.3.0"); it is a human-facing
# release label only and is not used by the staleness check.  BUILD_COMMIT
# is the most recent commit *that touched src/fortran/*, not the repo HEAD.
# This way commits that change only Python/docs/etc do not flag the binary
# as stale -- only commits that actually modify the Fortran source do.
# BUILD_DIRTY is scoped the same way: tracked uncommitted changes under
# src/fortran/ flip it to "dirty".
#
# The recipe runs on every `make` (via the FORCE prerequisite below) so
# it always reflects current state, but writes via a tmp+cmp+mv pattern:
# the file's mtime only bumps when the embedded stamp actually changes,
# letting Make's normal mtime-based dependency resolution skip recompiles
# when nothing has changed.
$(VERSION_F90): FORCE
	@if git rev-parse HEAD >/dev/null 2>&1; then \
	    COMMIT=$$(git log -1 --format=%H HEAD -- $(FORT_SRC_DIR) 2>/dev/null); \
	    [ -n "$$COMMIT" ] || COMMIT=unknown; \
	    TAG=$$(git describe --tags --abbrev=0 2>/dev/null); \
	    [ -n "$$TAG" ] || TAG=unknown; \
	    if git diff --quiet HEAD -- $(FORT_SRC_DIR) 2>/dev/null; then DIRTY=clean; else DIRTY=dirty; fi; \
	else \
	    TAG=unknown; COMMIT=unknown; DIRTY=unknown; \
	fi; \
	printf 'module version_stamp\n  implicit none\n  character(len=*), parameter :: BUILD_TAG    = "%s"\n  character(len=*), parameter :: BUILD_COMMIT = "%s"\n  character(len=*), parameter :: BUILD_DIRTY  = "%s"\nend module version_stamp\n' \
	    "$$TAG" "$$COMMIT" "$$DIRTY" > $@.tmp; \
	if cmp -s $@.tmp $@ 2>/dev/null; then \
	    rm $@.tmp; \
	else \
	    mv $@.tmp $@; \
	fi

# Empty non-phony target: Make can never "find" it on disk, so it treats
# FORCE as always-newer-than-$(VERSION_F90) and re-fires that recipe on
# every build.  Marking $(VERSION_F90) itself .PHONY would also re-fire
# the recipe, but a .PHONY prerequisite is always considered out-of-date,
# which would cascade unconditional recompiles into every binary that
# depends on $(VERSION_F90).
FORCE:

# $(VERSION_F90) is passed BEFORE the program source on the compile line
# so its .mod file is produced first within a single compiler invocation,
# making the `use version_stamp` in the program resolvable.
$(BUILD_DIR)/micro_rates: $(FORT_SRC_DIR)/micro_rates.f90 $(VERSION_F90) $(BUILD_DIR)/kiss.o | $(BUILD_DIR)
	$(FORT) $(BUILD_DIR)/kiss.o $(VERSION_F90) $(FORT_SRC_DIR)/micro_rates.f90 -o $(BUILD_DIR)/micro_rates

# $(BUILD_DIR)/micro_wrapped: $(FORT_SRC_DIR)/micro_wrapped.f90 $(BUILD_DIR)/kiss.o
# 	$(FORT) $(BUILD_DIR)/kiss.o $(FORT_SRC_DIR)/micro_wrapped.f90 -o $(BUILD_DIR)/micro_wrapped

$(BUILD_DIR)/macro_diffuse_into_and_along__external: $(FORT_SRC_DIR)/macro_diffuse_into_and_along__external.f90 $(VERSION_F90) $(BUILD_DIR)/kiss.o | $(BUILD_DIR)
	$(FORT) $(BUILD_DIR)/kiss.o $(VERSION_F90) $(FORT_SRC_DIR)/macro_diffuse_into_and_along__external.f90 -o $(BUILD_DIR)/macro_diffuse_into_and_along__external

$(BUILD_DIR)/macro_diffuse_into_and_along__internal: $(FORT_SRC_DIR)/macro_diffuse_into_and_along__internal.f90 $(VERSION_F90) $(BUILD_DIR)/kiss.o | $(BUILD_DIR)
	$(FORT) $(BUILD_DIR)/kiss.o $(VERSION_F90) $(FORT_SRC_DIR)/macro_diffuse_into_and_along__internal.f90 -o $(BUILD_DIR)/macro_diffuse_into_and_along__internal

$(LIB_DIR)/kiss.so: $(C_SRC_DIR)/kiss.c | $(LIB_DIR)
	$(C) -fPIC -shared -o $(LIB_DIR)/kiss.so $(C_SRC_DIR)/kiss.c

$(BUILD_DIR)/kiss.o: $(C_SRC_DIR)/kiss.c | $(BUILD_DIR)
	$(C) -c $(C_SRC_DIR)/kiss.c -o $(BUILD_DIR)/kiss.o
#	gcc -c -std=c99 $(C_SRC_DIR)/kiss.c -o $(BUILD_DIR)/kiss.o

# Output directories (order-only prerequisites): created on demand so a
# fresh checkout needs no manual `mkdir`.  Neither dir is tracked in git.
$(BUILD_DIR) $(LIB_DIR):
	$(MKDIR) -p $@

# Remove built artifacts.  Both dirs are recreated on demand by the next build.
clean:
	rm -rf $(BUILD_DIR) $(LIB_DIR)

# clean plus the generated (gitignored) version stamp source.
clobber: clean
	rm -f $(VERSION_F90)

help:
	@echo "Targets:"
	@echo "  build    (default) build Fortran binaries + lib/kiss.so"
	@echo "  fort     build only the Fortran binaries (needs ifort)"
	@echo "  shared   build only lib/kiss.so (needs gcc)"
	@echo "  all      alias for build"
	@echo "  clean    remove ./bin and ./lib"
	@echo "  clobber  clean + remove the generated version_stamp.f90"
