"""Preflight check that a Fortran binary matches the current source tree.

Each live Fortran binary embeds its build commit and dirty state via the
``version_stamp`` module (generated by the Makefile from ``git rev-parse HEAD``
and ``git diff`` of ``src/fortran/``).  At runtime each binary supports
``<executable> --version``, which prints
``"<commit> <state> <compiler-info>"`` and exits.  The compiler info is
ignored by the preflight check but included so the binary's build
environment is recoverable from its own output.

This module queries that output and compares it against the current source
tree before a simulation launches.  Any disagreement in either the commit
hash or the ``src/fortran/`` dirty bit raises :class:`StaleBinaryError`.
The caller may opt out via ``allow_stale=True`` (typically wired to the
``--allow-stale-binary`` CLI flag or the ``LYSIS_ALLOW_STALE_BINARY=1`` env
var), in which case the mismatch is downgraded to a :class:`UserWarning`,
a loud banner is returned for the caller to prepend to the Fortran stdout
log file, and override metadata is returned for stamping onto the HDF5
group.
"""

import os
import subprocess
import warnings
from pathlib import Path
from typing import Optional

from ...config.constants import CONST
from ._git import _git, _package_repo_root

__all__ = [
    "StaleBinaryError",
    "query_binary_version",
    "gather_binary_provenance",
    "gather_fortran_source_provenance",
    "allow_stale_from_env",
    "verify_binary_matches_source",
]


class StaleBinaryError(RuntimeError):
    """Raised when a Fortran binary's stamp disagrees with src/fortran/."""


def query_binary_version(
    executable: "Path | str", *, timeout: float = 5.0
) -> tuple[str, str, str]:
    """Run ``<executable> --version`` and parse its single-line stamp.

    :param executable: Path to the Fortran binary.
    :param timeout: Seconds to wait for the subprocess; on timeout the
        result is ``("unknown", "unknown", "unknown")``.
    :return: ``(commit_hash, dirty_state, compiler)`` parsed from the
        binary's stdout — the first three whitespace-separated tokens
        of the first line.  The compiler-info field is everything after
        the second whitespace gap, so it may itself contain spaces.
        Returns ``("unknown", "unknown", "unknown")`` for any failure
        mode (missing binary, non-zero exit, empty output, fewer than
        two tokens).  When only the first two tokens are present, the
        compiler field is ``"unknown"`` and the binary is still treated
        as resolvable for the staleness check.
    :rtype: tuple[str, str, str]
    """
    try:
        result = subprocess.run(
            [str(executable), "--version"],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except (FileNotFoundError, OSError, subprocess.TimeoutExpired):
        return ("unknown", "unknown", "unknown")
    if result.returncode != 0:
        return ("unknown", "unknown", "unknown")

    lines = result.stdout.strip().splitlines()
    if not lines:
        return ("unknown", "unknown", "unknown")
    parts = lines[0].split(maxsplit=2)
    if len(parts) < 2:
        return ("unknown", "unknown", "unknown")
    compiler = parts[2] if len(parts) == 3 else "unknown"
    return (parts[0], parts[1], compiler)


def gather_binary_provenance(executable: "Path | str") -> dict:
    """Gather binary provenance attrs from ``<executable> --version``.

    Pure data gather — never raises, no warnings.  Used by
    :meth:`~lysis.dataio.datastore.DataStore.stamp_provenance` to record
    what binary actually produced the simulation output.  Stamped on
    every ``run-*`` invocation, not just stale-binary overrides.

    :param executable: Path to the Fortran binary.
    :return: Dict keyed by :data:`CONST.BINARY_COMMIT_ATTR`,
        :data:`CONST.BINARY_DIRTY_ATTR`, :data:`CONST.BINARY_COMPILER_ATTR`.
        Values are ``"unknown"`` on any failure mode.
    :rtype: dict
    """
    commit, dirty, compiler = query_binary_version(executable)
    return {
        CONST.BINARY_COMMIT_ATTR: commit,
        CONST.BINARY_DIRTY_ATTR: dirty,
        CONST.BINARY_COMPILER_ATTR: compiler,
    }


def gather_fortran_source_provenance() -> tuple[str, str]:
    """Return ``(commit, dirty_state)`` for the current ``src/fortran/`` subtree.

    The commit is the most recent one *that touched* ``src/fortran/`` —
    not the repo HEAD — so commits that change only Python/docs/etc do
    not flag an otherwise-current binary as stale.  The dirty bit
    mirrors exactly what the Makefile checks
    (``git diff --quiet HEAD -- src/fortran``); both sides are scoped
    identically so the comparison is symmetric.

    :return: ``(commit, dirty_state)`` where ``dirty_state`` is one of
        ``"clean"``, ``"dirty"``, or ``"unknown"`` (the last when git is
        unavailable or the repo root cannot be located).
    :rtype: tuple[str, str]
    """
    repo_root = _package_repo_root()
    if repo_root is None:
        return ("unknown", "unknown")

    fortran_path = repo_root / "src" / "fortran"
    commit = _git(
        ["log", "-1", "--format=%H", "HEAD", "--", str(fortran_path)],
        repo_root,
    )
    if not commit:
        return ("unknown", "unknown")

    try:
        result = subprocess.run(
            [
                "git", "-C", str(repo_root),
                "diff", "--quiet", "HEAD", "--", str(fortran_path),
            ],
            check=False,
            capture_output=True,
        )
    except (FileNotFoundError, OSError):
        return (commit, "unknown")
    dirty = "dirty" if result.returncode != 0 else "clean"
    return (commit, dirty)


def allow_stale_from_env() -> bool:
    """Return ``True`` if ``LYSIS_ALLOW_STALE_BINARY`` is set to a truthy value.

    Accepted truthy strings (case-insensitive): ``1``, ``true``, ``yes``,
    ``on``.  Anything else (including unset) is ``False``.
    """
    raw = os.environ.get(CONST.LYSIS_ALLOW_STALE_BINARY_ENV, "").strip().lower()
    return raw in {"1", "true", "yes", "on"}


def _banner_text(
    *,
    executable: str,
    binary_commit: str,
    binary_dirty: str,
    source_commit: str,
    source_dirty: str,
) -> str:
    bar = "=" * 78
    return (
        f"{bar}\n"
        "WARNING: STALE FORTRAN BINARY -- preflight version check was OVERRIDDEN\n"
        f"{bar}\n"
        f"  executable:    {executable}\n"
        f"  binary stamp:  {binary_commit} ({binary_dirty})\n"
        f"  source stamp:  {source_commit} ({source_dirty})\n"
        "  This simulation's output was produced by a Fortran binary that\n"
        "  does NOT match the currently-checked-out src/fortran/.\n"
        "  Rebuild with `make` to restore a strict match.\n"
        f"{bar}\n"
    )


def verify_binary_matches_source(
    executable: "Path | str",
    *,
    allow_stale: Optional[bool] = None,
) -> dict:
    """Compare the binary's embedded stamp to the current source tree.

    :param executable: Path to the Fortran binary to check.
    :param allow_stale: Explicit override.  ``None`` (the default) consults
        :func:`allow_stale_from_env`; ``True`` downgrades a mismatch to a
        warning; ``False`` always raises on mismatch.
    :return: Empty dict on match.  On overridden mismatch, a dict
        containing ``"banner"`` (text to prepend to the Fortran stdout
        log file) and :data:`CONST.STALE_BINARY_OVERRIDE_ATTR` for
        forwarding to
        :meth:`~lysis.dataio.datastore.DataStore.stamp_provenance` as
        ``binary_override``.  The binary's commit/dirty/compiler are
        no longer included here — they are gathered fresh and stamped
        unconditionally via :func:`gather_binary_provenance`.
    :rtype: dict
    :raises StaleBinaryError: When the binary's stamp disagrees with the
        source tree and the override is not active.
    """
    if allow_stale is None:
        allow_stale = allow_stale_from_env()

    binary_commit, binary_dirty, _binary_compiler = query_binary_version(
        executable
    )
    source_commit, source_dirty = gather_fortran_source_provenance()

    matches = (
        binary_commit == source_commit
        and binary_dirty == source_dirty
        and binary_commit != "unknown"
    )
    if matches:
        return {}

    msg = (
        f"Fortran binary at {executable} reports build "
        f"{binary_commit} ({binary_dirty}); src/fortran/ is at "
        f"{source_commit} ({source_dirty}). Rebuild with `make`, or set "
        f"{CONST.LYSIS_ALLOW_STALE_BINARY_ENV}=1 / pass --allow-stale-binary "
        f"to run anyway."
    )
    if not allow_stale:
        raise StaleBinaryError(msg)

    warnings.warn(msg, UserWarning, stacklevel=2)
    return {
        "banner": _banner_text(
            executable=str(executable),
            binary_commit=binary_commit,
            binary_dirty=binary_dirty,
            source_commit=source_commit,
            source_dirty=source_dirty,
        ),
        CONST.STALE_BINARY_OVERRIDE_ATTR: True,
    }
