"""Preflight check that a Fortran binary matches the current source tree.

Each live Fortran binary embeds its release tag, build commit, and dirty
state via the ``version_stamp`` module (generated by the Makefile from
``git describe --tags --abbrev=0``, ``git rev-parse HEAD``, and ``git diff``
of ``src/fortran/``).  At runtime each binary supports
``<executable> --version``, which prints
``"<tag> <commit> <state> <compiler-info>"`` and exits.  The tag and
compiler info are ignored by the preflight check (which keys on commit and
dirty state) but are included so the binary's release label and build
environment are recoverable from its own output.

This module queries that output and compares it against the current source
tree before a simulation launches.  Any disagreement in either the commit
hash or the ``src/fortran/`` dirty bit raises :class:`StaleBinaryError`.
The caller may opt out via ``allow_stale=True`` (typically wired to the
``--allow-stale-binary`` CLI flag or the ``LYSIS_ALLOW_STALE_BINARY=1`` env
var), in which case the mismatch is downgraded to a :class:`UserWarning`,
a loud banner is returned for the caller to prepend to the Fortran stdout
log file, and override metadata is returned for stamping onto the HDF5
group.
"""

import os
import re
import subprocess
import tempfile
import warnings
from pathlib import Path
from typing import Optional

from ...config.constants import CONST
from ._git import _git, _package_repo_root

__all__ = [
    "StaleBinaryError",
    "query_binary_version",
    "gather_binary_provenance",
    "gather_historical_binary_provenance",
    "gather_fortran_source_provenance",
    "allow_stale_from_env",
    "verify_binary_matches_source",
]

#: Compiler binaries known to the lysis Fortran Makefile.  Order is
#: priority order when scanning for the first match in a build log.
_FORTRAN_COMPILERS: tuple[str, ...] = ("ifx", "ifort", "gfortran")


class StaleBinaryError(RuntimeError):
    """Raised when a Fortran binary's stamp disagrees with src/fortran/."""


def query_binary_version(
    executable: "Path | str", *, timeout: float = 5.0
) -> tuple[str, str, str]:
    """Run ``<executable> --version`` and parse its single-line stamp.

    The binary prints ``"<tag> <commit> <state> <compiler-info>"`` — the
    release tag (``git describe --tags --abbrev=0``) first, followed by the
    ``src/fortran/`` commit, the dirty bit, and the compiler string.  The
    tag is human-facing only; the staleness check uses the commit and dirty
    state, so this function drops the leading tag token and returns the
    remaining three fields.

    :param executable: Path to the Fortran binary.
    :param timeout: Seconds to wait for the subprocess; on timeout the
        result is ``("unknown", "unknown", "unknown")``.
    :return: ``(commit_hash, dirty_state, compiler)`` — the second, third,
        and (joined) remaining whitespace-separated tokens of the first
        line.  The compiler-info field is everything after the third
        whitespace gap, so it may itself contain spaces.  Returns
        ``("unknown", "unknown", "unknown")`` for any failure mode (missing
        binary, non-zero exit, empty output, fewer than three tokens).
        When only the first three tokens are present (tag, commit, state),
        the compiler field is ``"unknown"`` and the binary is still treated
        as resolvable for the staleness check.
    :rtype: tuple[str, str, str]
    """
    try:
        result = subprocess.run(
            [str(executable), "--version"],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except (FileNotFoundError, OSError, subprocess.TimeoutExpired):
        return ("unknown", "unknown", "unknown")
    if result.returncode != 0:
        return ("unknown", "unknown", "unknown")

    lines = result.stdout.strip().splitlines()
    if not lines:
        return ("unknown", "unknown", "unknown")
    parts = lines[0].split(maxsplit=3)
    if len(parts) < 3:
        return ("unknown", "unknown", "unknown")
    compiler = parts[3] if len(parts) == 4 else "unknown"
    return (parts[1], parts[2], compiler)


def gather_binary_provenance(executable: "Path | str") -> dict:
    """Gather binary provenance attrs from ``<executable> --version``.

    Pure data gather — never raises, no warnings.  Used by
    :meth:`~lysis.dataio.datastore.DataStore.stamp_provenance` to record
    what binary actually produced the simulation output.  Stamped on
    every ``run-*`` invocation, not just stale-binary overrides.

    :param executable: Path to the Fortran binary.
    :return: Dict keyed by :data:`CONST.BINARY_COMMIT_ATTR`,
        :data:`CONST.BINARY_DIRTY_ATTR`, :data:`CONST.BINARY_COMPILER_ATTR`.
        Values are ``"unknown"`` on any failure mode.
    :rtype: dict
    """
    commit, dirty, compiler = query_binary_version(executable)
    return {
        CONST.BINARY_COMMIT_ATTR: commit,
        CONST.BINARY_DIRTY_ATTR: dirty,
        CONST.BINARY_COMPILER_ATTR: compiler,
    }


def gather_fortran_source_provenance() -> tuple[str, str]:
    """Return ``(commit, dirty_state)`` for the current ``src/fortran/`` subtree.

    The commit is the most recent one *that touched* ``src/fortran/`` —
    not the repo HEAD — so commits that change only Python/docs/etc do
    not flag an otherwise-current binary as stale.  The dirty bit
    mirrors exactly what the Makefile checks
    (``git diff --quiet HEAD -- src/fortran``); both sides are scoped
    identically so the comparison is symmetric.

    :return: ``(commit, dirty_state)`` where ``dirty_state`` is one of
        ``"clean"``, ``"dirty"``, or ``"unknown"`` (the last when git is
        unavailable or the repo root cannot be located).
    :rtype: tuple[str, str]
    """
    repo_root = _package_repo_root()
    if repo_root is None:
        return ("unknown", "unknown")

    fortran_path = repo_root / "src" / "fortran"
    commit = _git(
        ["log", "-1", "--format=%H", "HEAD", "--", str(fortran_path)],
        repo_root,
    )
    if not commit:
        return ("unknown", "unknown")

    try:
        result = subprocess.run(
            [
                "git", "-C", str(repo_root),
                "diff", "--quiet", "HEAD", "--", str(fortran_path),
            ],
            check=False,
            capture_output=True,
        )
    except (FileNotFoundError, OSError):
        return (commit, "unknown")
    dirty = "dirty" if result.returncode != 0 else "clean"
    return (commit, dirty)


def allow_stale_from_env() -> bool:
    """Return ``True`` if ``LYSIS_ALLOW_STALE_BINARY`` is set to a truthy value.

    Accepted truthy strings (case-insensitive): ``1``, ``true``, ``yes``,
    ``on``.  Anything else (including unset) is ``False``.
    """
    raw = os.environ.get(CONST.LYSIS_ALLOW_STALE_BINARY_ENV, "").strip().lower()
    return raw in {"1", "true", "yes", "on"}


def _banner_text(
    *,
    executable: str,
    binary_commit: str,
    binary_dirty: str,
    source_commit: str,
    source_dirty: str,
) -> str:
    bar = "=" * 78
    return (
        f"{bar}\n"
        "WARNING: STALE FORTRAN BINARY -- preflight version check was OVERRIDDEN\n"
        f"{bar}\n"
        f"  executable:    {executable}\n"
        f"  binary stamp:  {binary_commit} ({binary_dirty})\n"
        f"  source stamp:  {source_commit} ({source_dirty})\n"
        "  This simulation's output was produced by a Fortran binary that\n"
        "  does NOT match the currently-checked-out src/fortran/.\n"
        "  Rebuild with `make` to restore a strict match.\n"
        f"{bar}\n"
    )


def verify_binary_matches_source(
    executable: "Path | str",
    *,
    allow_stale: Optional[bool] = None,
    source_stamp: "Optional[tuple[str, str]]" = None,
) -> dict:
    """Compare the binary's embedded stamp to the current source tree.

    :param executable: Path to the Fortran binary to check.
    :param allow_stale: Explicit override.  ``None`` (the default) consults
        :func:`allow_stale_from_env`; ``True`` downgrades a mismatch to a
        warning; ``False`` always raises on mismatch.
    :param source_stamp: Optional pre-computed ``(commit, dirty)`` tuple
        to compare the binary against, in place of the default
        :func:`gather_fortran_source_provenance` lookup.  Allows a caller
        that has already resolved the source stamp (e.g. a Slurm master
        that has copied ``src/`` out to a staging directory outside the
        repository) to skip the in-process ``git`` query that would
        otherwise fail because the binary's directory is no longer inside
        a checkout.  ``None`` (the default) preserves the in-process git
        lookup.
    :type source_stamp: tuple[str, str] or None
    :return: Empty dict on match.  On overridden mismatch, a dict
        containing ``"banner"`` (text to prepend to the Fortran stdout
        log file) and :data:`CONST.STALE_BINARY_OVERRIDE_ATTR` for
        forwarding to
        :meth:`~lysis.dataio.datastore.DataStore.stamp_provenance` as
        ``binary_override``.  The binary's commit/dirty/compiler are
        no longer included here — they are gathered fresh and stamped
        unconditionally via :func:`gather_binary_provenance`.
    :rtype: dict
    :raises StaleBinaryError: When the binary's stamp disagrees with the
        source tree and the override is not active.
    """
    if allow_stale is None:
        allow_stale = allow_stale_from_env()

    binary_commit, binary_dirty, _binary_compiler = query_binary_version(
        executable
    )
    if source_stamp is not None:
        source_commit, source_dirty = source_stamp
    else:
        source_commit, source_dirty = gather_fortran_source_provenance()

    matches = (
        binary_commit == source_commit
        and binary_dirty == source_dirty
        and binary_commit != "unknown"
    )
    if matches:
        return {}

    msg = (
        f"Fortran binary at {executable} reports build "
        f"{binary_commit} ({binary_dirty}); src/fortran/ is at "
        f"{source_commit} ({source_dirty}). Rebuild with `make`, or set "
        f"{CONST.LYSIS_ALLOW_STALE_BINARY_ENV}=1 / pass --allow-stale-binary "
        f"to run anyway."
    )
    if not allow_stale:
        raise StaleBinaryError(msg)

    warnings.warn(msg, UserWarning, stacklevel=2)
    return {
        "banner": _banner_text(
            executable=str(executable),
            binary_commit=binary_commit,
            binary_dirty=binary_dirty,
            source_commit=source_commit,
            source_dirty=source_dirty,
        ),
        CONST.STALE_BINARY_OVERRIDE_ATTR: True,
    }


# ---------------------------------------------------------------------------
# Historical-build provenance synthesis
# ---------------------------------------------------------------------------
#
# When ``lysis run-{micro,macro} --fortran-commit <ref>`` builds a binary
# from an old commit, the binary's own ``--version`` flag may not exist
# (added later in history) or may report a commit different from what the
# user requested.  We need a provenance dict shaped like the output of
# :func:`gather_binary_provenance` so it can flow through the same
# stamping pipeline.  The two non-obvious pieces are:
#
# - **commit / dirty**: take from the resolved git SHA (clean by
#   construction, since we extracted from git).
# - **compiler**: mirror what current binaries report — the string from
#   ``iso_fortran_env.compiler_version()``.  Get it the same way the
#   Makefile does: ask the compiler itself, by building and running a
#   tiny stub.  See :func:`_probe_iso_fortran_env_compiler_version`.


def _identify_compiler_binary(build_log: "Path | None") -> Optional[str]:
    """Return the Fortran compiler basename that actually ran the build.

    Scans *build_log* line-by-line and returns the first whitespace-
    delimited token that matches a known compiler basename (``ifx``,
    ``ifort``, ``gfortran``).  Returns ``None`` when no log is given or
    no match is found.

    :param build_log: Path to the captured ``make`` stdout/stderr log, or
        ``None`` if no log was kept.
    :type build_log: Path or None
    :return: Compiler basename (e.g. ``"ifort"``) or ``None``.
    :rtype: str or None
    """
    if build_log is None:
        return None
    try:
        text = Path(build_log).read_text(errors="replace")
    except (OSError, UnicodeDecodeError):
        return None
    pattern = re.compile(
        r"\b(" + "|".join(re.escape(c) for c in _FORTRAN_COMPILERS) + r")\b"
    )
    match = pattern.search(text)
    if match is None:
        return None
    return match.group(1)


def _probe_iso_fortran_env_compiler_version(
    compiler: str,
    *,
    module_wrapper: Optional[list[str]] = None,
    timeout: float = 30.0,
) -> Optional[str]:
    """Compile and run a tiny stub that prints ``iso_fortran_env.compiler_version()``.

    Mirrors exactly the mechanism that current Fortran binaries use to
    embed their compiler identification in ``--version`` output: the F2008
    intrinsic ``compiler_version()`` contributed by the compiler itself
    at compile time.  Compiling with the same binary that built the
    historical Fortran code guarantees a byte-for-byte equivalent string.

    :param compiler: Compiler binary name (e.g. ``"gfortran"``,
        ``"ifort"``, ``"ifx"``).  Must be discoverable on ``PATH`` —
        or, when *module_wrapper* is given, on the ``PATH`` after the
        module is loaded.
    :type compiler: str
    :param module_wrapper: Optional argv prefix that wraps the compile
        and run steps in an LMod-aware shell, e.g.
        ``["bash", "-c", "module purge && module load intel-compilers/2023 && exec \"$@\"", "--"]``.
        ``None`` (the default) invokes the compiler directly in the
        current environment.
    :type module_wrapper: list[str] or None
    :param timeout: Per-subprocess timeout in seconds.
    :type timeout: float
    :return: The first line of the stub's stdout (e.g.
        ``"GCC version 11.4.0"``), or ``None`` if any step failed.
    :rtype: str or None
    """
    stub = (
        "program compiler_id\n"
        "    use iso_fortran_env, only: compiler_version\n"
        "    implicit none\n"
        "    print '(a)', trim(compiler_version())\n"
        "end program\n"
    )
    with tempfile.TemporaryDirectory(prefix="lysis-compiler-probe-") as td:
        src = Path(td) / "probe.f90"
        exe = Path(td) / "probe"
        src.write_text(stub)
        compile_argv = [compiler, "-o", str(exe), str(src)]
        run_argv = [str(exe)]
        if module_wrapper is not None:
            compile_argv = [*module_wrapper, *compile_argv]
            run_argv = [*module_wrapper, *run_argv]
        try:
            result = subprocess.run(
                compile_argv,
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
        except (FileNotFoundError, OSError, subprocess.TimeoutExpired):
            return None
        if result.returncode != 0 or not exe.exists():
            return None
        try:
            result = subprocess.run(
                run_argv,
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired):
            return None
        if result.returncode != 0:
            return None
        first = result.stdout.splitlines()
        if not first:
            return None
        return first[0].strip() or None


def _module_wrapper_argv(modules: Optional[str]) -> Optional[list[str]]:
    """Build the bash-wrapper argv used to load LMod modules around a subprocess.

    :param modules: Space-separated list of LMod module specs, e.g.
        ``"intel-compilers/2023"`` or
        ``"intel-compilers/2024 SciPy-bundle/2023.07"``, forwarded verbatim
        to ``module load``; or ``None`` to skip wrapping.
    :type modules: str or None
    :return: argv list with ``"exec \"$@\""`` as the bash body so the
        wrapped command's exit status is preserved verbatim, or ``None``
        when *modules* is ``None``.
    :rtype: list[str] or None
    """
    if modules is None:
        return None
    script = (
        "[ -z \"${LMOD_CMD:-}\" ] && [ -f /etc/profile.d/lmod.sh ] "
        "&& source /etc/profile.d/lmod.sh; "
        f"module purge && module load {modules} && exec \"$@\""
    )
    return ["bash", "-c", script, "--"]


def gather_historical_binary_provenance(
    executable: "Path | str",
    *,
    resolved_sha: str,
    build_log: "Path | None" = None,
    modules: Optional[str] = None,
) -> dict:
    """Build a binary-provenance dict for a binary rebuilt from an older commit.

    Drop-in alternative to :func:`gather_binary_provenance`, intended
    for the ``lysis run-{micro,macro} --fortran-commit <ref>`` workflow.
    First tries the binary's own ``--version`` output (cheap, and if the
    binary supports it and reports the requested commit, that's already
    the authoritative answer).  Falls back to synthesising the dict when
    ``--version`` is unsupported or reports a different commit:

    - ``binary_commit`` = *resolved_sha* (the SHA we extracted from git).
    - ``binary_dirty`` = ``"clean"`` (we extracted from a clean git tree).
    - ``binary_compiler`` = result of
      :func:`_probe_iso_fortran_env_compiler_version`, identifying the
      compiler from *build_log* and running it on a tiny stub to capture
      ``iso_fortran_env.compiler_version()`` — the exact string a
      ``--version``-capable binary would have embedded.

    Always sets :data:`CONST.BINARY_SOURCE_ATTR` to
    ``f"historical:{resolved_sha}"`` so the deviation is auditable from
    the HDF5 file alone.

    :param executable: Path to the rebuilt Fortran binary.  Used only
        for the initial ``--version`` probe; if synthesis is required,
        the binary is not executed.
    :type executable: pathlib.Path or str
    :param resolved_sha: Full git SHA the binary was built from
        (resolved upstream via ``git rev-parse <ref>^{commit}``).
    :type resolved_sha: str
    :param build_log: Path to the captured ``make`` log used to identify
        which compiler binary actually ran.  ``None`` skips the probe
        and the result is ``"unknown"`` for *binary_compiler* in the
        synthesis path.
    :type build_log: pathlib.Path or None
    :param modules: Space-separated list of LMod module specs to load
        around the stub compile/run pair (e.g. ``"intel-compilers/2023"``).
        Should match the modules that wrapped ``make``.  ``None`` (default)
        runs the probe in the current environment.
    :type modules: str or None
    :return: Dict keyed by :data:`CONST.BINARY_COMMIT_ATTR`,
        :data:`CONST.BINARY_DIRTY_ATTR`, :data:`CONST.BINARY_COMPILER_ATTR`,
        :data:`CONST.BINARY_SOURCE_ATTR`.  All values are strings;
        unknown fields are ``"unknown"``.
    :rtype: dict
    """
    commit, dirty, compiler = query_binary_version(executable)
    if commit == resolved_sha and commit != "unknown":
        return {
            CONST.BINARY_COMMIT_ATTR: commit,
            CONST.BINARY_DIRTY_ATTR: dirty,
            CONST.BINARY_COMPILER_ATTR: compiler,
            CONST.BINARY_SOURCE_ATTR: f"historical:{resolved_sha}",
        }

    compiler_name = _identify_compiler_binary(build_log)
    if compiler_name is None:
        probed = None
    else:
        probed = _probe_iso_fortran_env_compiler_version(
            compiler_name,
            module_wrapper=_module_wrapper_argv(modules),
        )
    return {
        CONST.BINARY_COMMIT_ATTR: resolved_sha,
        CONST.BINARY_DIRTY_ATTR: "clean",
        CONST.BINARY_COMPILER_ATTR: probed or "unknown",
        CONST.BINARY_SOURCE_ATTR: f"historical:{resolved_sha}",
    }
