#!/bin/bash

# use below when using gprof
#setenv GMON_OUT_PREFIX 'gmon.out'

# --mca mpi_show_mca_params 1 --mca mpi_abort_delay -1

module purge
module load OpenMPI

cd ~/git/UCO-OpResearch/BloodClotting/bin
mpirun --tag-output ./c_macro

# for MPICH without slurm:
#HYDRA_TOPO_DEBUG=1 /home/Bryan/shared/mpich-3.4/bin/mpiexec --hosts=node1,node2 -np 14 --bind-to socket --map-by hwthread -prepend-rank ./ParallelMacro
