"""Debug script: execute the modified micro_rates binary for every run in
``data/lat-allocate-test/`` and collect the dumped Lat matrices into a
single human-readable text file.

The Fortran binary has been patched to print the Lat matrix between
``===BEGIN_LAT===`` / ``===END_LAT===`` markers and then ``stop`` before
the Gillespie simulation loop. ``micro_simulations`` is additionally
overridden to 10 here so that (a) this script stays cheap even if the
early-stop is ever removed and (b) the post-Lat allocations stay small.
"""

import dataclasses
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from lysis.execution.fortran_micro import FortranMicro  # noqa: E402

DATA_DIR = REPO / "data" / "lat-allocate-test"
EXECUTABLE = REPO / "bin" / "micro_rates"
OUT_FILE = DATA_DIR / "lat_matrices.txt"

BEGIN = "===BEGIN_LAT==="
END = "===END_LAT==="


def extract_lat_block(stdout: str) -> str:
    lines = stdout.splitlines()
    try:
        i = lines.index(BEGIN)
        j = lines.index(END, i + 1)
    except ValueError:
        return "<<MISSING Lat block>>\n" + stdout
    return "\n".join(lines[i : j + 1])


def main() -> None:
    runs = sorted(p.stem for p in DATA_DIR.glob("*.h5"))
    print(f"Found {len(runs)} runs in {DATA_DIR}")
    with open(OUT_FILE, "w") as out_fh:
        out_fh.write(f"Lat matrix dump for runs in {DATA_DIR}\n")
        out_fh.write(f"(generated by {Path(__file__).name})\n\n")
        for run_code in runs:
            hdf5_path = DATA_DIR / f"{run_code}.h5"
            runner = FortranMicro.from_hdf5(
                hdf5_path,
                executable=str(EXECUTABLE),
                out_file_code="_lat_debug",
            )
            runner.run.micro_params = dataclasses.replace(
                runner.run.micro_params, micro_simulations=10
            )
            cmd = runner.exec_command()
            nodes = runner.run.micro_params.nodes_in_micro_row
            print(f"[{run_code}] nodes={nodes}")
            result = subprocess.run(
                cmd,
                cwd=str(REPO),
                check=True,
                capture_output=True,
                text=True,
            )
            block = extract_lat_block(result.stdout)
            out_fh.write("=" * 72 + "\n")
            out_fh.write(f"RUN: {run_code}\n")
            out_fh.write(f"nodes_in_micro_row={nodes}\n")
            out_fh.write(f"command: {' '.join(cmd)}\n")
            out_fh.write("=" * 72 + "\n")
            out_fh.write(block)
            out_fh.write("\n\n")
    print(f"Wrote {OUT_FILE}")


if __name__ == "__main__":
    main()
